### ISSUE TITLE
Only shows files not containing flow, doesnt update

### ISSUE THREAD

**Issue by ncrmro** [cajacko/flow-check#1]
At the moment I can only get 

Does not contain @flow: ./src/index.js

It never actually updates the files.

**Comment by cajacko** [comment]
Have you tried running it with `flowcheck --skip-check`? I don't use or maintain this package anymore. Instead I use eslint and the flowtype plugin: https://github.com/gajus/eslint-plugin-flowtype. With the `require-valid-file-annotation` rule on

**Comment by cajacko** [comment]
How are you running the command? In the terminal or on a CI? If you run it without `--skip-check` it should give you an interactive prompt to confirm adding the tag to the files. If you're running this on a CI it might not do anything.

**Comment by ncrmro** [comment]
I've used  `yarn flowcheck` and `yarn flowcheck --skip-check` with no result. I will check out eslint + flow, as that seem like a more optimal solution.

**Comment by cajacko** [comment]
Yeah, I built this before I found that. The eslint route works much nicer. I'll update the README for this project saying it's no longer maintained and broken

**Comment by cajacko** [comment]
#https://github.com/cajacko/flow-check/commit/23312afa7a527cb7c64cc3ae13e15b77d2872bce
